### ISSUE TITLE
Homura, Human Ascendant // Homura's Essence has no flipside Oracle text

### ISSUE THREAD

**Issue by csuhta** [scryfall/gatherer-bugs#1]
No Oracle text is visible for the Homura's Essence's side, and it also says the enchantment side is 2/2

http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=84716

WotC Incident: 180430-001043

**Comment by Mervius** [comment]
This appears to have been fixed on Gatherer, btw. Not sure when but just checked today and it has the correct text.

**Comment by scarletcs** [comment]
Hooray! Thanks for the spot.
