### ISSUE TITLE
All summon must be replaced by creature type (example: Old Fogey)

### ISSUE THREAD

**Issue by JayDi85** [scryfall/gatherer-bugs#104]
[Old Fogey](https://scryfall.com/card/und/67/old-fogey)
Summon — Dinosaur

[Wiki told](https://mtg.fandom.com/wiki/Summon) that "summon" is obsolete word and was replaced by "creature" 15 years ago.

Rules:

> Summon (Obsolete)
>     Older creature cards were printed with “Summon [creature type]” on their type lines. All such cards have received errata in the Oracle card reference to say “Creature — [creature type].” (Many of these cards’ creature types have also been updated.) See Creature.

**Comment by NilsEnevoldsen** [comment]
The obsolete term is a deliberate joke for this silver-bordered card.

**Comment by csuhta** [comment]
Like Nils said, this is intentional on WotC's/Gatherer's part <https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=479456>
