### ISSUE TITLE
Missing cards from Arena Beginner Set (ANB)

### ISSUE THREAD

**Issue by nickmccurdy** [scryfall/gatherer-bugs#106]
Unlike Scryfall, Gatherer doesn't have Arena only cards, such as [Hallowed Priest](https://scryfall.com/card/anb/9/hallowed-priest) [(ANB)](https://scryfall.com/sets/anb).

**WotC Submission Number:** 2129729

**Comment by spacemonaut** [comment]
✅ Confirmed fixed
