### ISSUE TITLE
Hanweir Militia Captain and Heir to the Night yield Runtime Errors (any page, any set)

### ISSUE THREAD

**Issue by dskloet** [scryfall/gatherer-bugs#109]
The following 4 cards cause errors in Gatherer:
Hanweir Militia Captain
Heir of Falkenrath
Heir to the Night
Westvale Cult Leader

If you search directly for any of these cards, you land on an error page (https://dskl.net/screen/Xjg0OwTjsO1zOAFTlqYI).
And if you list the cards from Jumpstart: Historic Horizons and click on any of these cards, you get a similar error page.
https://gatherer.wizards.com/Pages/Search/Default.aspx?set=[%22Jumpstart%3a+Historic+Horizons%22]

**WotC Submission Number:**
I submitted the problem to WotC but did not receive any number.

**Comment by dskloet** [comment]
I have actually never received a submission number from WotC for any issue. I'm afraid my reports somehow don't work. Does someone else want to report this to WotC and add the number here?

**Comment by NilsEnevoldsen** [comment]
Submission confirmations are broken right now; it's not just you.

**Comment by spacemonaut** [comment]
Direct page links:

* Hanweir Militia Captain: https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=534624
* Heir of Falkenrath: https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=534665
* Heir to the Night: https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=534666
* Westvale Cult Leader: https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=534625

Other pages seem fine, e.g. [Winged Shepherd](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=534640) works fine.

**Comment by odininon** [comment]
This has been fixed.
