### ISSUE TITLE
Mine, Mine, Mine! has incorrect Oracle text

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/gatherer-bugs#11]
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=9787

Mine, Mine, Mine! has two errors in its Oracle text. The card names are missing punctuation.

It says:

> When Mine, Mine, Mine enters the battlefield, each player puts their library into their hand.
> Players have no maximum hand size and don't lose the game for drawing from an empty library.
> Each player can't cast more than one spell each turn.
> When Mine, Mine, Mine leaves the battlefield, each player shuffles their hand and graveyard into their library.

It should be:

> When Mine, Mine, Mine! enters the battlefield, each player puts their library into their hand.
> Players have no maximum hand size and don't lose the game for drawing from an empty library.
> Each player can't cast more than one spell each turn.
> When Mine, Mine, Mine! leaves the battlefield, each player shuffles their hand and graveyard into their library.

WotC Incident: 180501-000760

https://github.com/scryfall/feedback/issues/432

**Comment by spacemonaut** [comment]
duplicates #58
