### ISSUE TITLE
Watcher for Tomorrow has incorrect Oracle reminder text

### ISSUE THREAD

**Issue by april** [scryfall/gatherer-bugs#114]
Describe the problem
Watcher for Tomorrow's reminder text for Hideaway is:

> When this land enters the battlefield, look at the top four cards of your library, exile one face down, then put the rest on the bottom in a random order.

Instead of `this creature`

[Watcher for Tomorrow](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=464025)

**WotC Submission Number:**

**Comment by NilsEnevoldsen** [comment]
Appears to be fixed.

**Comment by spacemonaut** [comment]
✅ Confirmed fixed
