### ISSUE TITLE
Secret Lair version of Zndrsplt, Eye of Wisdom breaks Scryfall API contract

### ISSUE THREAD

**Issue by esperpanorama** [scryfall/gatherer-bugs#115]
The JSON for `Zndrsplt, Eye of Wisdom` (`id: d5dfd236-b1da-4552-b94f-ebf6bb9dafdf`) breaks Scryfall API contract. It is missing the fields `oracle_id` and `cmc` which are marked `non-null` in the API specification at https://scryfall.com/docs/api/cards.

However, both fields appear in the two `card_face` objects for Zndrsplt.

As this seems Scryfall-related I have not created a Gatherer bug. Please let me know in case this is Gatherer related. I'll then post the bug over there.

**Comment by csuhta** [comment]
These are some of the first reversible promos, they have two distinct Magic cards on either side. Many of the properties were moved into the `card_faces` array to handle the possibility of two disparate Magic cards on one piece of cardboard. We're working on documentation to address this new type.

This repo is only for notating problems on Gatherer that affect downstream consumers (like Scryfall), for further API questions, you can use http://scryfall.com/contact
