### ISSUE TITLE
Unable to submit contact form on the Scryfall Website

### ISSUE THREAD

**Issue by Meerkov** [scryfall/gatherer-bugs#118]
Describe the problem
Provide a link to the problematic page(s) if possible

https://scryfall.com/contact

I've tried submitting bugs to Scryfall, but no confirmation email is ever sent, and the page just sits on a white screen after submission. This was the only way I could find to reach out.

Sorry for clogging your gatherer project.

**WotC Submission Number:** 12345

**Comment by csuhta** [comment]
If you are receiving a white screen, you are likely tripping up our bot catching code. Make sure you are not using browser plugins that automatically fill in text for you too form fields, or try submitting using an incognito window.

**Comment by Meerkov** [comment]
It's nice that you closed the bug, but it happens without plugins in an
incognito window too. You probably should open a GitHub location to submit
bugs. Because you aren't receiving actually bugs in the scryfall website
because I can't actually submit.
