### ISSUE TITLE
All Gotcha cards have incorrect Oracle text

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/gatherer-bugs#12]
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=74244
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=74303
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=74359
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=74322
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=74293
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=74286
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=74337
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=74277
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=74339
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=74346
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=74349

These cards have errors in their Oracle text. "Gotcha!" is missing its exclamation point.

They say:

> …you may say "Gotcha"

They should say:

> …you may say "Gotcha!"

WotC Incident: 180501-000762

**Comment by spacemonaut** [comment]
duplicates #58
