### ISSUE TITLE
Cards specific to some language are not searchable in Gatherer

### ISSUE THREAD

**Issue by ichorid** [scryfall/gatherer-bugs#122]
For instance, the number of cards returned for a search for the name "Shade" is 24 if your language is "Traditional Chinese", but 35 if it is "English".

I'd expect everything to be searchable instead.

**Comment by NilsEnevoldsen** [comment]
I cannot replicate this. For example Cinder Shade does appear here for me: https://gatherer.wizards.com/Pages/Search/Default.aspx?action=advanced&subtype=+[%22Shade%22]

**Comment by NilsEnevoldsen** [comment]
The language setting restricts the search to prints that exist in that language. I think this is a deliberate choice rather than a bug.
