### ISSUE TITLE
The CMC and Type lines are broken for all cards

### ISSUE THREAD

**Issue by scarletcs** [scryfall/gatherer-bugs#128]
Related: Gatherer shouldn't be using the term _converted mana cost_ (CMC) at all; see #129.

---

For all cards for a while now, the layout of all cards has been a little bit broken around the CMC and type lines:

![pointy arrow](https://user-images.githubusercontent.com/4585677/186412063-a2d4f048-f388-47ff-b5ca-4fa43e5a3b34.png)

This is caused by the Converted Mana Cost line overflowing its bounds, and the Type line wrapping up into it:

![inspector: cmc line](https://user-images.githubusercontent.com/4585677/186412065-fd9b05d3-98a7-4288-a724-429a3caae5e6.png)
![inspector: type line](https://user-images.githubusercontent.com/4585677/186412075-e9c30493-9673-4703-9eb4-6bc9619307eb.png)

The more direct cause is that the labels of each row uses `float: left`. They shouldn't be using float at all because, well, this happens when you do that. Instead this table should be using flex layout, grid layout, or an actual table.

Incidentally, the problem would not occur if Gatherer swapped to the term "Mana Value", which it should really do anyway (again, #129). It should _also_ resolve the root cause layout error anyway since the layout rule of using `float: left` is unsound and the same layout issue could resurface in the future.

![mana value label](https://user-images.githubusercontent.com/4585677/186413043-543954a2-474a-4720-aeda-b3587751f4e1.png)

(Eagle-eyed readers will notice the "Converted Mana Cost" text label is also unusually small; the font size is dropped down to 70% of normal on this label alone. This font size rule can be dropped if they swap to mana value, and it is dropped in the above mockup screenshot.)

![70% font size](https://user-images.githubusercontent.com/4585677/186413047-75988a97-beb6-4b70-95f5-7365a556f902.png)

**WotC Submission Number:** https://magic-support.wizards.com/hc/en-us/requests/2899078

**Comment by odininon** [comment]
This has been fixed.
