### ISSUE TITLE
Gatherer still uses Converted Mana Cost instead of Mana Value

### ISSUE THREAD

**Issue by scarletcs** [scryfall/gatherer-bugs#129]
As of Strixhaven's release, _Magic: the Gathering_ has deprecated the term _converted mana cost_ in favour of the new (equivalent) term _mana value._ This became the case a year and a half ago, on April 16, 2021. See: [Strixhaven release notes](https://magic.wizards.com/en/articles/archive/feature/strixhaven-school-mages-and-commander-2021-edition-release-notes-2021-04-16).

Despite this change Gatherer still uses the deprecated terms _converted mana cost_ and _CMC_ instead of _mana value_ and/or _MV_.

## Advanced search

![2022-08-24_13-08-59_firefox](https://user-images.githubusercontent.com/4585677/186415262-ebcac23c-1b87-4e38-a4bd-aefb4bfb573b.png)

## Card pages

![2022-08-24_13-09-12_firefox](https://user-images.githubusercontent.com/4585677/186415265-e8f5dbb9-3d18-4037-9a2c-675b29b18ba4.png)

(For the broken layout in this screenshot, see #128)

**WotC Submission Number:** https://magic-support.wizards.com/hc/en-us/requests/2899078

**Comment by odininon** [comment]
This has been updated.
