### ISSUE TITLE
"Ach! Hans, Run!" has incorrect Oracle text

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/gatherer-bugs#13]
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=73935

"Ach! Hans, Run!" has an error in its Oracle text. The card name is missing punctuation.

It says:

> At the beginning of your upkeep, you may say "Ach Hans, run It's the . . ." and the name of a creature card. If you do, search your library for a card with that name, put it onto the battlefield, then shuffle your library. That creature gains haste. Exile it at the beginning of the next end step.

It should be:

> At the beginning of your upkeep, you may say "Ach! Hans, run! It's the . . ." and the name of a creature card. If you do, search your library for a card with that name, put it onto the battlefield, then shuffle your library. That creature gains haste. Exile it at the beginning of the next end step.

WotC Incident: 180501-000766

**Comment by spacemonaut** [comment]
duplicates #58
