### ISSUE TITLE
All Unfinity legendary creatures (even eternal-legal) have vanished from Gatherer

### ISSUE THREAD

**Issue by scarletcs** [scryfall/gatherer-bugs#140]
Every single legendary creature in Unfinity has been removed from Gatherer sometime since October 9th, 2022. A search for [all legends in Unfinity or Unfinity (Acorn)][leg] returns only Comet and Space Beleren, the two planeswalkers in Unfinity. This affects even eternal-legal legends: [Ambassador Blorpityblorpboop](https://scryfall.com/card/unf/161/ambassador-blorpityblorpboop) no longer has a Gatherer page to reference. In total, [11 eternal-legal legendary creatures](https://scryfall.com/search?q=t%3Alegendary+t%3Acreature+format%3Alegacy+set%3Aunfinity&unique=cards&as=grid&order=name) no longer exist on Gatherer.

[leg]: https://gatherer.wizards.com/Pages/Search/Default.aspx?action=advanced&type=+[%22Legendary%22]&set=|[%22unfinity%22]|[%22Unfinity%20(Acorn)%22]

We have broad evidence that lots of these cards did exist on Gatherer at some point. For example, #135 records links and screenshots to Vorthos's regular and showcase prints. These two links should point to Vorthos's page: [Vorthos](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=580793), [Vorthos's Showcase](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=580593). Today they just redirect to Gatherer's home page.

For more examples, [all of these legendary creature prints on Scryfall](https://scryfall.com/search?q=set%3Aunf+type%3Alegendary+is%3Amultiverse&order=name&as=grid&unique=prints) have an associated multiverse ID and all of their “view on gatherer” links will now just point to gatherer's home.

There may be other cards missing, but these at least are the ones I can definitely discover and pin down. It may be worth noting that all the legendary creatures are also all the cards with showcase treatments, and #135 reported an error with some of the showcase treatments (but only the Acorn ones).

**Comment by NilsEnevoldsen** [comment]
Fixed.

**Comment by scarletcs** [comment]
Fix was only for eternal-legal cards. I've opened a separate issue to cover the acorn cards:

* #172
