### ISSUE TITLE
The simple search text bar behaves differently on the front page vs on other pages

### ISSUE THREAD

**Issue by scarletcs** [scryfall/gatherer-bugs#141]
Gatherer's front page (https://gatherer.wizards.com/Pages/Default.aspx) offers a simple search text input that takes “search terms”.

Another search text input exists in the header at the top of any other search or card page on Gatherer. It looks identical and also takes “search terms”.

1. Simple search
   ![simple search bar](https://user-images.githubusercontent.com/4585677/210076465-45c228ec-aefa-40b9-96c7-2b9b5b8e4632.png)

2. Header search
   ![header search bar](https://user-images.githubusercontent.com/4585677/210076466-04673cac-ce0f-468c-a3f7-2cd1401c8264.png)

However, these two search bars behave completely differently. The first searches card _text_, but the second searches by card _name_. An input of `spring mind` generates different URLs depending on which search bar you use:

1. Simple search: `https://gatherer.wizards.com/Pages/Search/Default.aspx?text=+[spring]+[mind]`
2. Header earch: `https://gatherer.wizards.com/Pages/Search/Default.aspx?name=+[spring]+[mind]`

Good UX practice would be that identical inputs behave identically. A button should always be pressable; a delete button always deletes; two search bars that look like the same search bar control but in another spot should behave the same.

# Screenshots

![simple search: input](https://user-images.githubusercontent.com/4585677/210076287-7ec7994a-01a0-46f5-b15e-28c49ff65851.png)
![simple search: results](https://user-images.githubusercontent.com/4585677/210076289-d9c333c7-5e60-422e-a52e-2900c57632ef.png)
![header search: input](https://user-images.githubusercontent.com/4585677/210076290-17574730-a0e7-46e3-9c09-466bb7ab2b1f.png)
![header search: results](https://user-images.githubusercontent.com/4585677/210076291-a50541a4-c141-42f8-be0f-87aac8e28d89.png)

**Comment by odininon** [comment]
The behavior you describe is due to not having name selected for simple search. 
![image](https://github.com/scryfall/gatherer-bugs/assets/2147898/f925c8ff-f561-434d-b62a-24d2729dc450)

**Comment by scarletcs** [comment]
You're right. I investigated again not long after filing this and realized that was the case as well, but forgot to close this!

Closing as not an issue.
