### ISSUE TITLE
Brothers' War exists on Companion but cannot be searched

### ISSUE THREAD

**Issue by scarletcs** [scryfall/gatherer-bugs#144]
Although cards from The Brothers' War exist on Hunterer and can be searched and viewed in Companion, the set itself cannot be searched at all.

<img width="400" src="https://user-images.githubusercontent.com/4585677/210083381-0a87a0c4-11b9-4f43-b1c4-dc5d95ba65b8.png">

<img width="400" src="https://user-images.githubusercontent.com/4585677/210083390-7b3f90ea-9870-4363-8e7c-0b298aa8408a.png">
<img width="400" src="https://user-images.githubusercontent.com/4585677/210083396-7086fd6d-2521-452f-b6d2-18776ea6e93e.png">

**Comment by odininon** [comment]
This has been fixed.

**Comment by scarletcs** [comment]
This is fixed now:

![Screenshot_20240521-144323.png](https://github.com/scryfall/gatherer-bugs/assets/4585677/f722867e-1715-4dd4-8e10-eaf831b73ba1)
