### ISSUE TITLE
Kaboom! has incorrect Oracle text

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/gatherer-bugs#15]
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=39559

Kaboom! has an error in its Oracle text. The card name is missing punctuation.

It says:

> Choose any number of target players or planeswalkers. For each of them, reveal cards from the top of your library until you reveal a nonland card, Kaboom deals damage equal to that card's converted mana cost to that player or planeswalker, then you put the revealed cards on the bottom of your library in any order.

It should be:

> Choose any number of target players or planeswalkers. For each of them, reveal cards from the top of your library until you reveal a nonland card, Kaboom! deals damage equal to that card's converted mana cost to that player or planeswalker, then you put the revealed cards on the bottom of your library in any order.

**WotC Incident ID:** 180512-000523

**Comment by spacemonaut** [comment]
duplicates #58
