### ISSUE TITLE
Dominaria Remastered is not on Gatherer

### ISSUE THREAD

**Issue by scarletcs** [scryfall/gatherer-bugs#150]
[Dominaria Remastered](https://scryfall.com/sets/dmr?as=grid&order=set) was prereleased on Friday the 6th and released on Friday the 13th. Sets usually go up on Gatherer sometime soon before prerelease, or at least in the week between prerelease and release. As of today, it is still not present on Gatherer.

It cannot be found in the search sets dropdown:
![2023-01-14_22-32-13_firefox](https://user-images.githubusercontent.com/4585677/212500026-c69f066b-19cc-4e88-8865-4c3fafa02d1e.png)

[Auramancer](https://gatherer.wizards.com/Pages/Card/Printings.aspx?multiverseid=591430), the [first card in the set](https://scryfall.com/card/dmr/1/auramancer), does not have a printing for Dominaria Remastered.
![2023-01-14_22-32-40_firefox](https://user-images.githubusercontent.com/4585677/212500030-2870559d-ae5c-47ba-a176-b637d6b3abeb.png)

**Comment by csuhta** [comment]
This finally appeared on Gatherer
