### ISSUE TITLE
Sol Ring no longer makes mana, just oppresses elves/humans/dwarves

### ISSUE THREAD

**Issue by scarletcs** [scryfall/gatherer-bugs#156]
[Sol Ring]'s card text no longer contains the actual text to generate mana.

Someone appears to have instead added [the ring verse](https://tolkiengateway.net/wiki/Ring_Verse) that's written on [the text from LTC](https://scryfall.com/card/ltc/408/sol-ring).

> Neldë Cormar Aranin Eldaron nu i Vilya  
> Otso Heruin Naucoron mi ondomardi  
> Nertë Fírimoin qualambar  
> Minë Moriherun morimahalmaressë  
> Morinóressë yassë nár Mordor

[sol ring]: https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=605880

![2023-07-10_16-34-01_firefox](https://github.com/scryfall/gatherer-bugs/assets/4585677/41fd271f-104e-4a8f-a2ec-3707ec03b6a5)

**Comment by scarletcs** [comment]
(I super shamelessly stole this title joke from Niuttuc)

**Comment by odininon** [comment]
This has been fixed.
