### ISSUE TITLE
Clock of DOOOOOOOOOOOOM! has an error in its Oracle text

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/gatherer-bugs#16]
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=439531

Clock of DOOOOOOOOOOOOM! has an error in its Oracle text. The CRANK! counter is missing punctuation.

It says:

> {4}, {T}: Move the CRANK counter to your Contraption deck's next sprocket and crank any number of that sprocket's Contraptions.

It should be:

> {4}, {T}: Move the CRANK! counter to your Contraption deck's next sprocket and crank any number of that sprocket's Contraptions.

**WotC Incident ID:** 180512-000527

**Comment by spacemonaut** [comment]
duplicates #58
