### ISSUE TITLE
The Black Gate and Bilbo, Birthday Celebrant have combined rulings

### ISSUE THREAD

**Issue by a-tangible-human-skull** [scryfall/gatherer-bugs#161]
https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=620766
https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=620734

![image](https://github.com/scryfall/gatherer-bugs/assets/121780660/f2dcb146-41e1-49d4-882a-7275410b7467)

Currently fixed on Scryfall

**Comment by NilsEnevoldsen** [comment]
Fixed.
