### ISSUE TITLE
Infernal Spawn of Evil has incorrect Oracle text

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/gatherer-bugs#17]
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=9779

Infernal Spawn of Evil has an error in its Oracle text. It is missing an exclamation point.

It says:

> Flying, first strike
> {1}{B}, Reveal Infernal Spawn of Evil from your hand, Say "It's coming": Infernal Spawn of Evil deals 1 damage to target opponent or planeswalker. Activate this ability only during your upkeep and only once each turn.

It should be:

> Flying, first strike
> {1}{B}, Reveal Infernal Spawn of Evil from your hand, Say "It's coming!": Infernal Spawn of Evil deals 1 damage to target opponent or planeswalker. Activate this ability only during your upkeep and only once each turn.

**WotC Incident ID:** 180512-000532

**Comment by spacemonaut** [comment]
duplicates #58
