### ISSUE TITLE
Dragonhawk, Fate's Tempest has a typo. Using dot instead of comma.

### ISSUE THREAD

**Issue by MarlonFolken** [scryfall/gatherer-bugs#178]
The creature [Dragonhawk, Fate's Tempest](https://scryfall.com/card/blb/132/dragonhawk-fates-tempest) has a typo into its profile text, not the image, but the table with text.

Current text: [...] At the beginning of your next end step. Dragonhawk deals 2 damage to each opponent [...]
Accurate text: [...] At the beginning of your next end step, Dragonhawk deals 2 damage to each opponent [...]

<img width="388" alt="Screenshot 2024-07-18 at 9 35 05 a m" src="https://github.com/user-attachments/assets/324444da-0139-4a90-b776-44fdca104c97">

**Comment by NilsEnevoldsen** [comment]
This issue tracker is for issues in Gatherer, not issues in Scryfall. You can use the "Report card issue" link on Scryfall to report errors with cards on Scryfall. (You don't have to report this one, I've already reported it based on this issue.)
