### ISSUE TITLE
Infernal Spawn of Infernal Spawn of Evil has incorrect Oracle text

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/gatherer-bugs#18]
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=73981

Infernal Spawn of Infernal Spawn of Evil has an error in its Oracle text. It is missing an exclamation point.

It says:

> Flying, first strike, trample
> Once each turn, while you're searching your library, you may pay {1}{B}, reveal Infernal Spawn of Infernal Spawn of Evil from your library and say "I'm coming, too" If you do, Infernal Spawn of Infernal Spawn of Evil deals 2 damage to a player of your choice.

It should be:

> Flying, first strike, trample
> Once each turn, while you're searching your library, you may pay {1}{B}, reveal Infernal Spawn of Infernal Spawn of Evil from your library and say "I'm coming, too!" If you do, Infernal Spawn of Infernal Spawn of Evil deals 2 damage to a player of your choice.

**WotC Incident ID:** 180512-000534

**Comment by spacemonaut** [comment]
duplicates #58
