### ISSUE TITLE
Scryfall reports all of PIP as "is:booster"==false

### ISSUE THREAD

**Issue by Meerkov** [scryfall/gatherer-bugs#184]
### Describe the problem

Scryfall ignores their private bug reporting mechanism and offers no public github reporting mechanism, so reporting this here for more visibility.

https://scryfall.com/search?q=set%3Apip+is%3Abooster&unique=cards&as=grid&order=rarity

Only 22 cards are "booster=true" in this set of 1000+ cards. Please fix thanks

**Comment by scarletcs** [comment]
Hi there. This repository is for recording bugs with [Gatherer](https://gatherer.wizards.com/Pages/Default.aspx) or the Magic: the Gathering mobile companion app. It is not for reporting issues with Scryfall. If you want to report an issue with Scryfall, you can [contact us directly](https://scryfall.com/contact).
