### ISSUE TITLE
Scryfall wrong rarity (special, bonus, promo)

### ISSUE THREAD

**Issue by JayDi85** [scryfall/gatherer-bugs#32]
You are closed scryfall tracker, that's why I'm wrote that issue here...

Gatherer have non standard rarity for cards like "special" or "promo". Scryfall mark that cards as "rare".

![shot_180921_224759](https://user-images.githubusercontent.com/8344157/45900302-69d27100-bdf0-11e8-8f5a-a93662dec161.png)

As example: Ghost Ship

![shot_180921_224642](https://user-images.githubusercontent.com/8344157/45900246-45769480-bdf0-11e8-9291-87a934ee7a86.png)

![shot_180921_224654](https://user-images.githubusercontent.com/8344157/45900267-545d4700-bdf0-11e8-89b0-232d16fb3363.png)

**Comment by csuhta** [comment]
Please report Scryfall issues here: https://scryfall.com/feedback

This repo is for tracking public bugs on Gatherer
