### ISSUE TITLE
Missing Astral cards

### ISSUE THREAD

**Issue by ogamespec** [scryfall/gatherer-bugs#49]
Astral cards are missing:

https://magic.wizards.com/en/articles/archive/feature/astral-cards-2009-02-12

BTW, Aswan Jaguar was even printed as oversized card:

https://www.ebay.com/itm/Magic-The-Gathering-Oversize-6x9-Aswan-Jaguar-Card-Very-Cool-Artwork-/172967721125

![image](https://user-images.githubusercontent.com/5828819/54342155-c484b100-464c-11e9-8881-4d21a84d5f11.png)

**Comment by csuhta** [comment]
Have you submitted a support ticket to WotC? I’d be interested to know if they consider Astral out-of-scope for Gatherer.

**Comment by ogamespec** [comment]
Done, waiting reply.

**Comment by ogamespec** [comment]
> Hello,
> 
> Thank you for contacting us about this issue!
> 
> The cards you are referring to are not cards that have playable real-world equivalents, and are only found in the MicroProse game from 1997.
> 
> In any case, we appreciate you taking the time to write in with your feedback on this issue! I have gotten your feedback regarding the inclusion of non-printed cards in Gatherer up to the appropriate teams for review. While I cannot guarantee any further contacts concerning your feedback, I can assure you that we take all feedback submitted to us very seriously.
> 
> I’ll be glad to help you further if you have any other questions or concerns!
> 
> Alexander‍
> Wizards of the Coast

**Comment by crookedneighbor** [comment]
Sounds like they don’t intend to include them. Should this issue be closed now?

**Comment by spacemonaut** [comment]
Closed since Gatherer doesn't appear to consider this card in scope. This isn't unusual; most promos do not get catalogued in Gatherer.
