### ISSUE TITLE
Cards with flavor text in Gatherer with improperly escaped HTML tags

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/gatherer-bugs#51]
Some cards have improperly escaped HTML tags in their flavor text in an attempt to render italics.

Full list of English cards:
http://gatherer.wizards.com/Pages/Search/Default.aspx?action=advanced&flavor=+[&lt;]

e.g., Back to Basics (UMA):
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=456642

Erase (Not the Urza's Legacy One) (UNH) is an example of this done successfully; the strikethrough tags were [properly] not escaped:
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=74275

**WotC Submission Number:** 636487

**Comment by odininon** [comment]
This has been fixed.
