### ISSUE TITLE
Lost char in Russian Interface

### ISSUE THREAD

**Issue by BekoBou** [scryfall/gatherer-bugs#55]
Word "language" in Russian is "язык" (4 chars). Right now in interface lost the last 'к' — 'русский язы'.

https://scryfall.com/sets/m20/ru

P.S. Thank You for your great project. You are awesome!

**Comment by csuhta** [comment]
That's been fixed, thank you! 

In the future, please report issues with the Scryfall site at <https://scryfall.com/contact>. This project is for tracking bugs with the Gatherer website.
