### ISSUE TITLE
Embodiment of Agonies Missing Hybrid Mana symbol in rulings

### ISSUE THREAD

**Issue by crookedneighbor** [scryfall/gatherer-bugs#56]
The rulings on gatherer for hybrid mana do not include the hybrid mana symbol:

> Hybrid mana symbols are treated as the actual symbols, not as either of their two components individually. For example, [missing], Black, and Red are three different mana costs.

https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=466852

<img width="770" alt="Screen Shot 2019-07-10 at 8 34 38 AM" src="https://user-images.githubusercontent.com/2916945/60973505-0ae1d800-a2ee-11e9-979e-9435c46e6f8c.png">

**WotC Submission Number:** 771282 Hybrid Mana Symbol Missing in Rulings for Embodiment of Agonies

**Comment by NilsEnevoldsen** [comment]
Fixed!
