### ISSUE TITLE
Nim Deathmantle has an incorrect name in Chinese Simplified print data

### ISSUE THREAD

**Issue by spacemonaut** [scryfall/gatherer-bugs#57]
Nim Deathmantle (ZHS language) on Gatherer: https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=232477&printed=true

The printed name is listed as 泞族亡篷
The actual printed name is  泞族亡者头罩

This actual printed name can be seen on the card scan on the Gatherer page itself.

![firefox_2019-07-13_12-26-00](https://user-images.githubusercontent.com/4585677/61171019-74214f80-a569-11e9-8226-704441df642d.png)

**WotC Submission Number:** 776207

**Comment by luziferius** [comment]
Looks like it is fixed on Gatherer.

**Comment by csuhta** [comment]
So it is!
