### ISSUE TITLE
Elemental Resonance rulings have mis-formatted hybrid mana symbols

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/gatherer-bugs#59]
Elemental Resonance contains a ruling with "If its mana cost is (W/U)(W/U)…" In Gatherer, these should be replaced by the actual hybrid mana symbols.

https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=107369

https://scryfall.com/card/dis/83/elemental-resonance

**WotC Submission Number:** 885934

**Comment by csuhta** [comment]
Looks like this was fixed
