### ISSUE TITLE
Vanguarda de Alesha has a photograph instead of a card scan

### ISSUE THREAD

**Issue by csuhta** [scryfall/gatherer-bugs#64]
This card's picture on Gatherer is a photo of someone playing Magic: https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=393268&printed=true

![Image ashx](https://user-images.githubusercontent.com/769083/75942607-df08f900-5e60-11ea-930b-84dc4eb0d0f6.png)

**WotC Submission Number:**

**Comment by einstein95** [comment]
The photo is of Chris Pikula, from https://magic.wizards.com/en/articles/archive/week-was/back-future-2015-01-09

**Comment by spacemonaut** [comment]
This has been fixed.
