### ISSUE TITLE
Category mentioned in the readme no longer exists 

### ISSUE THREAD

**Issue by einstein95** [scryfall/gatherer-bugs#65]
[README.md](https://github.com/scryfall/gatherer-bugs/blob/master/README.md) states:
> At the moment you should use the "Rules Question" category (source)

However, the current available categories are:
* General Questions
* Permission Request
* Feedback
* Product Replacement
* Help with my DCI/PWP/Wizards Account
* MTGO Reimbursement Questionnaire
* Activity Kit
* Report Conduct
* Delete My Personal Information
* Request a Copy of My Personal Data
* Event Corrections Form
* Store and Event Feedback Form
* Gatherer Feedback
* Magic: The Gathering Companion Issues
* Wizards Online Store Product Replacement
* Wizards Online Store Product Returns
* Wizards Online Store Product Questions

**Comment by NilsEnevoldsen** [comment]
> Gatherer Feedback

😍

**Comment by csuhta** [comment]
Yay! They added a new category just for this! Readme has been updated
