### ISSUE TITLE
Unhinged cards have extra HTML italic tags

### ISSUE THREAD

**Issue by einstein95** [scryfall/gatherer-bugs#66]
On pages such as the one for "Chicken à la King" (https://gatherer.wizards.com/Pages/Card/Details.aspx?printed=true&multiverseid=479417), the value for "Card Text" contains extra (escaped) italic blocks around the already italic text.
![Screenshot from 2020-03-28 01-42-47](https://user-images.githubusercontent.com/2461173/77758748-62042480-7098-11ea-9ee0-7d263bcc49bf.png)

**WotC Submission Number:** None given

**Comment by odininon** [comment]
This has been fixed.
