### ISSUE TITLE
Jegantha has missing hybrid mana symbols in its ruling

### ISSUE THREAD

**Issue by spacemonaut** [scryfall/gatherer-bugs#69]
Jegantha, the Wellspring: https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=479742

![2020-04-18_11-01-39_firefox](https://user-images.githubusercontent.com/4585677/79634685-004d4c80-8164-11ea-8094-260d9894a925.png)

> Jegantha’s  companion ability compares the exact symbols in the mana costs of cards  in your deck. If any one card has the same symbol twice, such as {X}{X}{R} or , the companion condition isn’t satisfied. — 17/04/2020

This ruling is missing some mana symbols after the "or". According to [the Ikoria release notes](https://magic.wizards.com/en/articles/archive/feature/ikoria-lair-behemoths-and-commander-2020-edition-release-notes-2020-04-10) those symbols are {R/G}{R/G}, for the release notes say:

> Jegantha's companion ability compares the exact symbols in the mana costs of cards in your deck. If any one card has the same symbol twice, such as {X}{X}{R} or {r/g}{r/g}, the companion condition isn't satisfied.

**WotC Submission Number:** TBD

**Comment by NilsEnevoldsen** [comment]
Fixed.

**Comment by spacemonaut** [comment]
Confirmed fixed on Gatherer.
