### ISSUE TITLE
Gyruda in PT has only "Gyruda" for a name

### ISSUE THREAD

**Issue by spacemonaut** [scryfall/gatherer-bugs#70]
Gyruda, Doom of Depths, in PT: https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=482481&printed=true

The PT translation of Gyruda has only "Gyruda" for a name. The printed name should be "Gyruda, Ruina das Profundezas".

**WotC Submission Number:** TBD

**Comment by NilsEnevoldsen** [comment]
Fixed.
