### ISSUE TITLE
META: There's no Gatherer Feedback category

### ISSUE THREAD

**Issue by dskloet** [scryfall/gatherer-bugs#71]
The README.md here says:
"
Please report the issue to https://magic-support.wizards.com/hc/en-us/requests/new first.
Use the "Gatherer Feedback" category
"

But there is no such category. What is the correct way to report Gatherer bugs?

**Comment by NilsEnevoldsen** [comment]
#65 🤦

**Comment by dskloet** [comment]
If I look in the HTML, the option is there, but if you open the dropdown in the UI, it's not.

But I can tell from the HTML that it leads to
https://magic-support.wizards.com/hc/en-us/requests/new?ticket_form_id=360000421811
which seems to work.

**Comment by csuhta** [comment]
So this is a display bug on their site, maybe?

**Comment by csuhta** [comment]
Updated to directly link there, and also provide some other instructions https://github.com/scryfall/gatherer-bugs/commit/5aeaba4c123734e706d4c327c0e9c22eadc5ebee
