### ISSUE TITLE
Mystery Booster cards with rule text in Gatherer with improperly escaped HTML tags

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/gatherer-bugs#73]
Some Mystery Booster cards have improperly escaped HTML tags in their rule text in an attempt to render italics.

Full list of English cards:
https://gatherer.wizards.com/Pages/Search/Default.aspx?action=advanced&text=+%5B&lt;%5D

e.g., Abian, Luvion Usurper (MH1):
https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=476217

This is related to open issue 636487 (for reminder text) and to closed issue 732020 (for rule text that has since been fixed).

**WotC Submission Number:** [Did not (yet?) receive email confirmation]

(See #51, #53)

**Comment by spacemonaut** [comment]
Related: Jasconian Isle also includes an unclosed HTML tag.

![2021-04-17_14-50-41](https://user-images.githubusercontent.com/4585677/115115465-8aeda500-9f8c-11eb-8abf-24fdc208cf18.png)

**Comment by spacemonaut** [comment]
This is a regression of #53 and appears to be broadly affecting Mystery Booster cards:

![2021-11-23_15-07-01_firefox](https://user-images.githubusercontent.com/4585677/143049811-19bbe50a-943c-499e-ac75-4d75fd03e532.png)

**Comment by NilsEnevoldsen** [comment]
Fixed (again) (with the exception of [Bind//Liberate](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=476218)).
