### ISSUE TITLE
Colossus of Akros has incorrect Oracle text

### ISSUE THREAD

**Issue by csuhta** [scryfall/gatherer-bugs#8]
Colossus of Akros's oracle text says "{1}0", it should say "{10}". The mana symbol is not shown correctly.
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=373555

WotC incident: 180501-000134

**Comment by crookedneighbor** [comment]
Opened a second incident for this one. My poor colossus. 😢 

**WotC incident:** 771324
