### ISSUE TITLE
Time Spiral's Timeshifted cards aren't listed as legal in Modern

### ISSUE THREAD

**Issue by spacemonaut** [scryfall/gatherer-bugs#90]
The vast majority of Timeshifted cards from Time Spiral are listed as not legal in Modern.

* [Gatherer search for set: Timeshifted, format: NOT Modern](https://gatherer.wizards.com/Pages/Search/Default.aspx?action=advanced&set=+[%22Time%20Spiral%20%22Timeshifted%22%22]&format=+![%22Modern%22]) lists 117 Timeshifted cards as NOT LEGAL in Modern. They are not listed as banned; they are simply not listed as legal.
* [Gatherer search for set: Timeshifted, format: Modern](https://gatherer.wizards.com/Pages/Search/Default.aspx?action=advanced&set=+[%22Time%20Spiral%20%22Timeshifted%22%22]&format=+[%22Modern%22]) lists 5 cards.

The five legal cards are Disenchant, Dragon Whelp, Fiery Temper, Gaea's Blessing, Tormod's Crypt. These five are the only cards to be printed later in a standard-legal (or modern-legal) set: https://scryfall.com/search?q=in%3Atsb+date%3Etsp+%28st%3Acore+or+st%3Aexpansion%29

The keen-eyed among you would notice this adds up to 122, but there were only 121 Timeshifted cards. The extra is because Assault // Battery is listed twice: Assault is one result, Battery is another result.

**WotC Submission Number:** None provided

# Timeshifted cards listed as NOT LEGAL in Modern (117) (actually 116)
![2020-10-13_20-22-03_firefox](https://user-images.githubusercontent.com/4585677/95906230-cc10bc80-0d91-11eb-9585-8d1b94f4fa01.png)

### Example: Akroma

![2020-10-13_20-34-34_firefox](https://user-images.githubusercontent.com/4585677/95907497-8bb23e00-0d93-11eb-88c3-1b8ed303601c.png)

# Timeshifted cards listed as legal in Modern (5)
![2020-10-13_20-22-10_firefox](https://user-images.githubusercontent.com/4585677/95906241-ce731680-0d91-11eb-91ef-b75637cbe81b.png)

### Example: Gaea's Blessing

![2020-10-13_20-35-20_firefox](https://user-images.githubusercontent.com/4585677/95907570-a5ec1c00-0d93-11eb-9ec0-a0d58712ac8c.png)

**Comment by NilsEnevoldsen** [comment]
This is fixed.
