### ISSUE TITLE
Biomass Mutation has a miscalculation in its rulings

### ISSUE THREAD

**Issue by spacemonaut** [scryfall/gatherer-bugs#92]
[Biomass Mutation](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=470733) has a ruling that says the following. You don't need to read this full text, I'll quote the important bit afterwards:

> Biomass Mutation overwrites any effects that set the power and/or toughness of a creature you control to a specific value. Effects that modify power and/or toughness but don’t set them to a specific value (like the one created by Giant Growth), power/toughness changes from counters, and effects that switch a creature’s power and toughness will continue to apply. For example, say you control a 1/1 creature that’s getting +4/+2 from an Aura, has a +1/+1 counter on it, and is affected by an effect that switches its power and toughness. This creature is 4/6. If you cast Biomass Mutation with X equal to 4, the creature would become 7/9 (4/4, +4/+2 from the Aura, +1/+1 from the counter, then switch power and toughness).

The important part is the maths in the example:

> For example, say you control a 1/1 creature that’s getting +4/+2 from an Aura, has a +1/+1 counter on it, and is affected by an effect that switches its power and toughness. This creature is 4/6. If you cast Biomass Mutation with X equal to 4, the creature would become 7/9 (4/4, +4/+2 from the Aura, +1/+1 from the counter, then switch power and toughness).

The aura is described as +4/+2, but the calculations appear to be handling the aura as a +2/+4 aura instead.

The ruling should be corrected to describe it as a +2/+4 aura.

**WotC Submission Number:** TBD

**Comment by cooperaa** [comment]
From https://scryfall.com/card/a25/75/twisted-image :
```
Effects that switch power and toughness apply after all other effects that change power and/or toughness, regardless of which effect was created first.
```

In this case, it sounds like the Gatherer is mathing properly; the 4/4 gets +4/+2 from the aura and +1/+1 from the counter and _then_ the power and toughness is switched, becoming a 7/9.

**Comment by NilsEnevoldsen** [comment]
Agreed.
1. Biomass Mutation happens in layer 7b.
2. Aura and counter happen in layer 7c.
3. P/T switching happens in layer 7d.

**Comment by spacemonaut** [comment]
Thanks @cooperaa and @NilsEnevoldsen. My mistake. The ruling even calls out that we switch power and toughness at the end.

Not actually an error; closed. :)
