### ISSUE TITLE
Secret Lair: Walking Dead cards are listed as not legal in any format

### ISSUE THREAD

**Issue by spacemonaut** [scryfall/gatherer-bugs#94]
[The Walking Dead Shambles into Secret Lair](https://magic.wizards.com/en/articles/archive/news/walking-dead-shambles-secret-lair-2020-09-28) announced that the Walking Dead cards are ”legal in eternal formats“. However, all of the cards in this lair are listed on Gatherer as not legal in any formats. As much as I wish this were true, this seems to be an error.

* [Daryl](https://gatherer.wizards.com/Pages/Card/Printings.aspx?multiverseid=497506)
* [Glenn](https://gatherer.wizards.com/Pages/Card/Printings.aspx?multiverseid=497507)
* [Lucille](https://gatherer.wizards.com/Pages/Card/Printings.aspx?multiverseid=497516)
* [Michonne](https://gatherer.wizards.com/Pages/Card/Printings.aspx?multiverseid=497508)
* [Negan](https://gatherer.wizards.com/Pages/Card/Printings.aspx?multiverseid=497509)
* [Rick](https://gatherer.wizards.com/Pages/Card/Printings.aspx?multiverseid=497505)

![2021-01-03_18-17-49](https://user-images.githubusercontent.com/4585677/103485694-24cf7e80-4df0-11eb-98a8-42c30d80fc72.png)
![2021-01-03_18-18-09](https://user-images.githubusercontent.com/4585677/103485695-24cf7e80-4df0-11eb-98c7-7f78216f5085.png)
![2021-01-03_18-14-52_firefox](https://user-images.githubusercontent.com/4585677/103485688-2305bb00-4df0-11eb-8323-ced6cf71257f.png)
![2021-01-03_18-14-53](https://user-images.githubusercontent.com/4585677/103485690-239e5180-4df0-11eb-8e59-51a36ecf0fec.png)
![2021-01-03_18-14-56](https://user-images.githubusercontent.com/4585677/103485692-2436e800-4df0-11eb-9118-c1638f18ad53.png)
![2021-01-03_18-14-57](https://user-images.githubusercontent.com/4585677/103485693-2436e800-4df0-11eb-9723-148c33cd0fd5.png)

**WotC Submission Number:** Reported, but no email response and no submission number

**Comment by NilsEnevoldsen** [comment]
This is fixed.
