### ISSUE TITLE
Omnath, Locus of Creation listed as legal in Standard and Brawl

### ISSUE THREAD

**Issue by spacemonaut** [scryfall/gatherer-bugs#95]
Gatherer lists Omnath, Locus of Creation as legal in Standard and Brawl. In the [October 12, 2020 B&R update](https://magic.wizards.com/en/articles/archive/news/october-12-2020-banned-and-restricted-announcement) Omnath was banned in both of these formats. There has been no subsequent unban announcement that I am aware of.

https://gatherer.wizards.com/Pages/Card/Printings.aspx?multiverseid=491883

![2021-01-04_19-42-49_firefox](https://user-images.githubusercontent.com/4585677/103572950-51a19580-4ec5-11eb-8541-e1fc901f953e.png)

**WotC Submission Number:** Reported, but no email response and no submission number

**Comment by NilsEnevoldsen** [comment]
Fixed.
