### ISSUE TITLE
Uro, Titan of Nature's Wrath listed as Standard legal

### ISSUE THREAD

**Issue by spacemonaut** [scryfall/gatherer-bugs#96]
Gatherer lists Uro, Titan of Nature's Wrath as legal in all formats. However in the [September 28, 2020 B&R update](https://magic.wizards.com/en/articles/archive/news/september-28-2020-banned-and-restricted-announcement-2020-09-28) Uro was banned in Standard. There has been no announcement unbanning Uro that I'm aware of.

https://gatherer.wizards.com/Pages/Card/Printings.aspx?multiverseid=476480

![2021-01-04_19-43-08_firefox](https://user-images.githubusercontent.com/4585677/103573114-9d543f00-4ec5-11eb-966e-b8770f77ebae.png)

**WotC Submission Number:** Reported, but no email response and no submission number

**Comment by NilsEnevoldsen** [comment]
This is fixed.
