### ISSUE TITLE
[STX] Devouring Tendrils rules typo

### ISSUE THREAD

**Issue by JayDi85** [scryfall/gatherer-bugs#99]
[Devouring Tendrils](https://scryfall.com/card/stx/126/devouring-tendrils)

Typos in card's text -- must be "if" instead "the":
* When **the** permanent you don’t control dies this turn, you gain 2 life.

**Comment by JayDi85** [comment]
All fine, sorry.

**Comment by spacemonaut** [comment]
Note: this was a report on an incorrect transcription on Scryfall, not Gatherer data.
